name: Publish Nuget

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
          8.0.x
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Integration Tests
      run: dotnet test test/WorkflowCore.IntegrationTests --configuration Release --no-build --verbosity normal -p:ParallelizeTestCollections=false
    - name: PostgreSQL Tests
      run: dotnet test test/WorkflowCore.Tests.PostgreSQL --configuration Release --no-build --verbosity normal -p:ParallelizeTestCollections=false
    - name: Pack WorkflowCore
      run: dotnet pack src/WorkflowCore --configuration Release --no-build
    - name: Pack WorkflowCore.DSL
      run: dotnet pack src/WorkflowCore.DSL --configuration Release --no-build
    - name: Pack WorkflowCore.Testing
      run: dotnet pack src/WorkflowCore.Testing --configuration Release --no-build
    - name: Pack EntityFramework
      run: dotnet pack src/providers/WorkflowCore.Persistence.EntityFramework --configuration Release --no-build
    - name: Pack PostgreSQL
      run: dotnet pack src/providers/WorkflowCore.Persistence.PostgreSQL --configuration Release --no-build
    - name: Pack Redis
      run: dotnet pack src/providers/WorkflowCore.Providers.Redis --configuration Release --no-build
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
